#!/usr/bin/env python3
"""
Package BPMN Definition - Create ZIP packages of BPMN definitions for review or deployment

This script packages validated BPMN definitions into ZIP files containing:
- BPMN XML file (IBM BAW version)
- Original JSON configuration file
- README with metadata and usage instructions

The script excludes preview files and is designed for cross-platform compatibility
(Windows, Linux, macOS) using Python's built-in zipfile module.

Usage:
    python package_bpmn_definition.py <config_file.json> [output_dir]
    
Example:
    python package_bpmn_definition.py business-processes/configs/Insurance/SimpleClaimSubmission.bpmn-config.json
    
Output:
    Creates: business-processes/packages/Insurance/SimpleClaimSubmission.zip
    Contains:
        - SimpleClaimSubmission.bpmn (IBM BAW version)
        - SimpleClaimSubmission.bpmn-config.json (original config)
        - README.md (metadata and instructions)
"""

import sys
import json
import zipfile
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any
from generate_bpmn import ConfigLoader


def load_config_metadata(config_path: Path) -> Dict[str, Any]:
    """
    Load metadata from BPMN configuration file
    
    Args:
        config_path: Path to the JSON config file
        
    Returns:
        Dictionary containing process metadata
    """
    with open(config_path, 'r', encoding='utf-8') as f:
        config = json.load(f)
    
    process_info = config.get('process', {})
    metadata = config.get('metadata', {})
    
    return {
        'process_id': process_info.get('id', 'unknown'),
        'process_name': process_info.get('name', 'Unknown Process'),
        'description': process_info.get('description', ''),
        'version': process_info.get('version', '1.0'),
        'context': metadata.get('business_context', metadata.get('context', 'General')),
        'source_document': metadata.get('source_document', ''),
        'created_date': metadata.get('created_date', datetime.now().isoformat()),
    }


def generate_readme(metadata: Dict[str, Any], config_filename: str, bpmn_filename: str) -> str:
    """
    Generate README content for the BPMN package
    
    Args:
        metadata: Process metadata dictionary
        config_filename: Name of the config file in the package
        bpmn_filename: Name of the BPMN file in the package
        
    Returns:
        README content as string
    """
    readme = f"""# {metadata['process_name']}

## Process Information

- **Process ID**: {metadata['process_id']}
- **Version**: {metadata['version']}
- **Business Context**: {metadata['context']}
- **Package Created**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Description

{metadata['description'] if metadata['description'] else 'No description provided.'}

## Package Contents

### 1. {bpmn_filename}
IBM Business Automation Workflow (BAW) BPMN 2.0 definition with IBM-specific extensions.
This file can be imported into IBM Process Designer.

### 2. {config_filename}
Original JSON configuration file used to generate the BPMN definition.
This file follows the schema defined in BPMN_tools/CONFIG_SCHEMA_DESIGN.md.

## Usage Instructions

### Importing into IBM BAW Process Designer

1. Open IBM Process Designer
2. Navigate to your Process App or Toolkit
3. Right-click on "Business Processes" and select "Import"
4. Select the `{bpmn_filename}` file from this package
5. Review and confirm the import

### Regenerating BPMN from Config

If you need to regenerate or modify the BPMN definition:

```bash
python BPMN_tools/generate_bpmn.py {config_filename} output.bpmn
```

This will create:
- `output.bpmn` - IBM BAW version
- `output-preview.bpmn` - Standard BPMN 2.0 for generic viewers

## Source Information

{f"**Source Document**: {metadata['source_document']}" if metadata['source_document'] else "Source document not specified."}

**Original Config Created**: {metadata['created_date']}

## Notes

- This package contains only the BPMN process definition
- Business objects and other dependencies must be packaged separately
- For complete toolkit packaging, use the BAW Package Manager mode

---

*Generated by BAW Blueprint Parser - BPMN Definition Packager*
"""
    return readme


def package_bpmn_definition(
    config_path: str,
    output_dir: Optional[str] = None,
    exclude_preview: bool = True
) -> Path:
    """
    Package BPMN definition into a ZIP file
    
    Args:
        config_path: Path to the JSON config file
        output_dir: Optional output directory (defaults to business-processes/packages/<context>/)
        exclude_preview: If True (default), exclude preview BPMN files from package
        
    Returns:
        Path to the created ZIP file
        
    Raises:
        FileNotFoundError: If config file doesn't exist
        ValueError: If config validation fails
    """
    config_file = Path(config_path)
    
    if not config_file.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")
    
    print(f"📦 Packaging BPMN definition from: {config_file}")
    
    # Load and validate configuration
    loader = ConfigLoader(standard_mode=False)
    loader.load_config(str(config_file))
    
    errors = loader.validate_config()
    if errors:
        raise ValueError(f"Configuration validation failed:\n" + "\n".join(errors))
    
    print("✅ Configuration validated successfully")
    
    # Load metadata
    metadata = load_config_metadata(config_file)
    process_name = config_file.stem.replace('.bpmn-config', '')
    
    # Determine output directory
    if output_dir:
        output_path = Path(output_dir)
    else:
        # Default: business-processes/packages/<context>/
        context = metadata['context']
        output_path = Path('business-processes') / 'packages' / context
    
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Generate BPMN XML (IBM BAW version only, no preview)
    print("🔨 Generating BPMN XML...")
    bpmn_xml = loader.generate_from_config()
    
    # Create temporary BPMN file
    bpmn_filename = f"{process_name}.bpmn"
    temp_bpmn_path = output_path / bpmn_filename
    
    with open(temp_bpmn_path, 'w', encoding='utf-8') as f:
        f.write(bpmn_xml)
    
    print(f"✅ BPMN XML generated: {bpmn_filename}")
    
    # Generate README
    config_filename = config_file.name
    readme_content = generate_readme(metadata, config_filename, bpmn_filename)
    
    # Create ZIP package
    zip_filename = f"{process_name}.zip"
    zip_path = output_path / zip_filename
    
    print(f"📦 Creating ZIP package: {zip_path}")
    
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Add BPMN file
        zipf.write(temp_bpmn_path, bpmn_filename)
        
        # Add original config file
        zipf.write(config_file, config_filename)
        
        # Add README
        zipf.writestr('README.md', readme_content)
    
    # Clean up temporary BPMN file
    temp_bpmn_path.unlink()
    
    print(f"\n✅ Successfully created BPMN definition package!")
    print(f"   📦 Package: {zip_path}")
    print(f"   📄 Contains:")
    print(f"      - {bpmn_filename} (IBM BAW BPMN)")
    print(f"      - {config_filename} (JSON config)")
    print(f"      - README.md (metadata & instructions)")
    print(f"\n   Process: {metadata['process_name']}")
    print(f"   Version: {metadata['version']}")
    print(f"   Context: {metadata['context']}")
    
    return zip_path


def main():
    """Main entry point for the script"""
    if len(sys.argv) < 2:
        print("Usage: python package_bpmn_definition.py <config_file.json> [output_dir]")
        print("\nCreates a ZIP package containing:")
        print("  - BPMN XML file (IBM BAW version)")
        print("  - Original JSON configuration")
        print("  - README with metadata and instructions")
        print("\nExample:")
        print("  python package_bpmn_definition.py business-processes/configs/Insurance/SimpleClaimSubmission.bpmn-config.json")
        print("\nDefault output location:")
        print("  business-processes/packages/<context>/<process-name>.zip")
        sys.exit(1)
    
    config_file = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else None
    
    try:
        package_bpmn_definition(config_file, output_dir)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()

# Made with Bob
